name: first-workflow
on: workflow_dispatch
jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps: 
      - name: print hello   
        run: echo "Hello cream"
      - name: print bye
        run: echo "bye bye" 
